defmodule Realworld.Repo.Migrations.AddComments do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    create table(:comments, primary_key: false) do
      add(:id, :uuid, null: false, primary_key: true)
      add(:body, :text, null: false)
      add(:created_at, :utc_datetime_usec, null: false, default: fragment("now()"))
      add(:updated_at, :utc_datetime_usec, null: false, default: fragment("now()"))
    end
  end

  def down do
    drop(table(:comments))
  end
end