defmodule Realworld.Repo.Migrations.AddUserIdentities do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    create(unique_index(:users, [:email], name: "users_unique_email_index"))

    create(unique_index(:users, [:username], name: "users_unique_username_index"))
  end

  def down do
    drop_if_exists(unique_index(:users, [:username], name: "users_unique_username_index"))

    drop_if_exists(unique_index(:users, [:email], name: "users_unique_email_index"))
  end
end