defmodule Realworld.Repo.Migrations.ChangePassword do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    alter table(:users) do
      modify(:password, :text, null: false)
      modify(:email, :text, null: false)
      modify(:username, :text, null: false)
    end
  end

  def down do
    alter table(:users) do
      modify(:username, :text, null: true)
      modify(:email, :text, null: true)
      modify(:password, :text, null: true)
    end
  end
end