defmodule Realworld.Repo.Migrations.AddUserAttrs do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    alter table(:users) do
      add :username, :text
      add :password, :text
      add :bio, :text
      add :image, :text
      add :token, :text
    end
  end

  def down do
    alter table(:users) do
      remove :token
      remove :image
      remove :bio
      remove :password
      remove :username
    end
  end
end