defmodule Realworld.Repo.Migrations.ChangePasswordColumn do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    rename(table(:users), :password, to: :hashed_password)
  end

  def down do
    rename(table(:users), :hashed_password, to: :password)
  end
end