defmodule Realworld.Repo.Migrations.AddArticleIdUserIdToComments do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    alter table(:comments) do
      add(
        :article_id,
        references(:articles,
          column: :id,
          name: "comments_article_id_fkey",
          type: :uuid,
          prefix: "public"
        )
      )

      add(
        :user_id,
        references(:users,
          column: :id,
          name: "comments_user_id_fkey",
          type: :uuid,
          prefix: "public"
        )
      )
    end
  end

  def down do
    drop(constraint(:comments, "comments_user_id_fkey"))

    drop(constraint(:comments, "comments_article_id_fkey"))

    alter table(:comments) do
      remove(:user_id)
      remove(:article_id)
    end
  end
end